id: P007104
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-17 12:41:52.585980
source_metadata:
  id: bdr:W1AC39
  title: དཔལ་རྡོ་རྗེ་འཇིགས་བྱེད་ཆེན་པོའི་དབང་བཤད་སྐུ་གསུམ་རིན་ཆེན་བང་མཛོད།
  author: ''
  volumes:
    244304e0a3754e8297a7b62d92ae182f:
      image_group_id: I2PD18861
      title: Volume 1 of dpal rdo rje 'jigs byed chen po'i dbang bshad sku gsum rin
        chen bang mdzod/
      volume_number: 1
      total_pages: 338
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
