id: P007104
initial_creation_type: ocr
source_metadata:
  id: bdr:W1AC39
  title: དཔལ་རྡོ་རྗེ་འཇིགས་བྱེད་ཆེན་པོའི་དབང་བཤད་སྐུ་གསུམ་རིན་ཆེན་བང་མཛོད།
  author: ''
  volumes:
    4a5d6797c5534ac7b5cea9fee39af2f6:
      image_group_id: I2PD18861
      title: ''
      volume_number: 1
      total_pages: 338
ebook_metadata:
  title: དཔལ་རྡོ་རྗེ་འཇིགས་བྱེད་ཆེན་པོའི་དབང་བཤད་སྐུ་གསུམ་རིན་ཆེན་བང་མཛོད།
  author: ''
  sku: P007104
  cover: cover.jpg
  layers:
  - pagination
